name: Core
version: 1.0.0
main: com.rowlingsrealm.core.CorePlugin

description: "Rowling's Realm's core plugin!"
authors: [Tyler Grissom]
website: http://rowlingsrealm.com

softdepend: [Magic]

commands:
  core:
    description: Check the Core version.
  discord:
    description: Fetch Discord link.
  faq:
    description: Fetch FAQ link.
  store:
    description: Fetch store link.
  website:
    description: Fetch website link.