name: PluginEssentials
version: 1.0.0
main: me.tylergrissom.pluginessentials.SpigotPlugin

description: "Provides a set of libraries for Spigot plugins."
authors: [Tyler Grissom]
website: http://tyler-g.net

commands:
  pluginessentials:
    description: Check the PluginEssentials version.